name: Deploy mkdocs (material) site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs + Material
        run: |
          pip install mkdocs-material

      - name: Build and deploy
        run: |
          cd mkdocs
          mkdocs gh-deploy --force
