site_name: HyEngine Documentation
site_url: https://hyengine.org/docs/
site_dir: ../docs
nav:
  - Getting Started:
      - Installation & Setup: getting-started/install.md
      - First Project: getting-started/first_project.md
      - Programming Quickstart: getting-started/programming_quickstart.md
  - Editor Manual:
      - Overview: editor/overview.md
      - Project Explorer: editor/project_explorer.md
      - Asset Manager: editor/asset_manager.md
      - TileSets: editor/tilesets.md
      - Project Items:
          - Sprites: editor/sprites.md
          - Tile Map: editor/tilemap.md
          - Text: editor/text.md
          - Particles: editor/particles.md
          - Spine: editor/spine.md
          - Audio: editor/audio.md
          - Entity: editor/entity.md
  - Engine Manual:
      - Overview: engine/overview.md
      - Coding Style: engine/code_style.md
      - Game Loop: engine/game_loop.md
      - Scene Nodes: engine/scene_nodes.md
      - Windows & Cameras: engine/windows_cameras.md
      - User Interface: engine/user_interface.md
  - Example Projects:
      - Audio: examples/audio.md
      - Multiwindow: examples/multiwindow.md
      - Text: examples/text.md
      - Spine: examples/spine.md